### ISSUE TITLE
What's your definition of vulnerability?

### ISSUE THREAD

**Issue by filerun** [EmreOvunc/FileRun-Vulnerabilities#1]
You're browsing FileRun applications folders that are supposed to be publicly accessible for the browsers to load web resources from them. Listing their contents... So what?

**Comment by EmreOvunc** [comment]
This is not recommended because the directory may contain files that are not normally exposed through links on the web site.

**Comment by filerun** [comment]
No they may not. Unless somebody puts them there. And then, why would somebody put files inside "public_html"/"www" if they didn't want them to be public?!
While we appreciate a useful vulnerability finding, you seem to have posted this just to make you look helpful. Otherwise there is absolutely no point in having a GitHub project describing.. well.. nothing.

P.S. You should report Apache, IIS, Nginx, etc. as having the vulnerability of listing directories and providing access to resources :)

**Comment by EmreOvunc** [comment]
You should learn what directory listing is. It is not about putting something in public folder.

P.S.  Your project has two more 0-day vulnerabilities, 1. SQL Injection, 2. Directory Traversal :))
